import Head from "next/head";
import styles from "@/styles/pages/Projects.module.scss";

import ItemList from "@/components/itemList";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { selectIcon } from "@/store";

export default function Projects() {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(selectIcon("projects"));
  }, []);
  return (
    <>
      <Head>
        <title>Salvatore Bisconti - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Projects}>
        <div className={styles.container}>
          <h2 className={styles.headerText}>PROJECTS</h2>
          <ItemList type="project" />
        </div>
      </main>
    </>
  );
}
