import Head from "next/head";
import styles from "@/styles/pages/Projects.module.scss";

import ItemList from "@/components/itemList";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.Projects}>
        <h2 className={styles.headerText}>MY PROJECTS</h2>
        <ItemList type="project" />
      </main>
    </>
  );
}
